---
kind: pipeline
name: build

steps:
- name: startnotify
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEB_URL
    channel: docker-image-builds
    template: >
        Build {{build.number}} of {{build.branch}} started. {{build.link}}  
- name: docker  
  image: plugins/docker
  #failure: ignore
  settings:
    username: 
      from_secret: docker_registry_username
    password: 
      from_secret: docker_registry_password
    repo: jarrodl/tfdevbox
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
      - ${DRONE_COMMIT_BRANCH}

---
kind: pipeline
name: end-notify

steps:
- name: endnotify
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEB_URL
    channel: docker-image-builds
    template: >
      {{#success build.status}}
        build {{build.number}} {{build.link}} Success. Container Built / Test / Uploaded - Nice One !
      {{else}}
        build {{build.number}} {{build.link}} Failed. Computer says No !
      {{/success}}
    #when:
    #  status: 
    #  - success
    #  - failure
  #depends_on:
  #  - build
  
  trigger:
    status:
      - success
      - failure